package com.yudzeen.pokemoncardtracker.core.model

enum class Variant {
    REGULAR,
    REVERSE_HOLO,
    HOLO,
    FULL_ART,
    ALTERNATE_ART,
    ACE_SPEC,
    PLAY_POKEMON_STAMPED,
    PLAY_POKEMON_STAMPED_REVERSE_HOLO,
    PLAY_POKEMON_REVERSE_HOLO,
    GYM_EVENT_STAMPED,
    PREMIER_BALL_LEAGUE_STAMPED,
    GREAT_BALL_LEAGUE_STAMPED,
    ULTRA_BALL_LEAGUE_STAMPED,
    MASTER_BALL_LEAGUE_STAMPED,
    LEAGUE_CUP_STAMPED,
    POKEMON_LEAGUE_STAMPED,
    POKEMON_LEAGUE_REVERSE_HOLO,
    CELEBRATIONS_STAMPED,
    IONO_ZONE_STAMPED
}